### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by imalisiddique** [WebFont/webfont_notepad#1]
Hi There,
How to install this plugin? I copied WebFontNpp to plugin folder but not working.

**Comment by xVir** [comment]
Hi, @alisiddique,
The repository contains only sources. Please download **npp.zip** from [releases](https://github.com/WebFont/webfont_notepad/releases/tag/v1.0) and unpack it in Notepad++ folder. Unpacking is demonstrated [here](https://youtu.be/waxvAWuR7qg).

Thanks!

**Comment by imalisiddique** [comment]
Thanks

**Comment by xVir** [comment]
@alisiddique you are welcome! :)
